# This is part of a custom mono repo setup I have.
# The folder structure is basically divided into an `app` and a `packages` folders.
# Codecov logging to codecov.io should be improved. Right now, it overwrites the previous one.
# Everything works except for the last stage, the Android Integration Tests.
# Working to make the Android tests work seems like a nightmare because of different
# versions incompatibility, something Apple does much better.

language: dart

env:
  global:
    - DARTSDK=./flutter/bin/cache/dart-sdk/bin
    - DARTFMT=$DARTSDK/dartfmt
    - FLUTTER=./flutter/bin/flutter
    - FLUTTER_GITHUB=https://github.com/flutter/flutter.git
    - CODECOV=https://codecov.io/bash
    - PACKAGES=packages

install:
  - git clone $FLUTTER_GITHUB -b stable --depth 1
  - $FLUTTER doctor
  - $FLUTTER pub get

jobs:
  include:
    - stage: Formatting
      script:
        - $DARTFMT -n $PACKAGES --set-exit-if-changed
