name: kroma_sport
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.8+15

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.1
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  flutter_feather_icons: ^2.0.0+1
  cached_network_image: ^3.0.0
  flutter_easyrefresh: ^2.2.1
  image_picker: ^0.7.4
  image_cropper: ^1.4.0
  shared_preferences: ^2.0.7
  intl_phone_number_input: ^0.7.0+2
  libphonenumber: ^2.0.2
  pin_input_text_field: ^4.0.0
  flutter_countdown_timer: ^4.1.0
  flutter_vector_icons: ^1.0.0
  multi_image_picker2: ^5.0.2
  timeago: ^3.0.2
  flutter_swiper_null_safety: ^1.0.1
  syncfusion_flutter_datepicker: ^20.4.52
  expandable: ^5.0.1
  intl: ^0.17.0
  flutter_picker: ^2.0.1
  flutter_time_picker_spinner:
    path: packages/flutter_time_picker_spinner-1.0.6+1-null-safety
  photo_view: ^0.12.0
  modal_bottom_sheet:
    git:
      url: https://github.com/followthemoney1/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet

  smooth_page_indicator: ^0.3.0-nullsafety.0
  google_maps_flutter: ^2.0.5
  geocoding: ^2.0.5
  location: ^4.1.1
  dotted_border: ^2.0.0
  flutter_svg: ^0.22.0
  line_icons: ^2.0.1
  toggle_switch: ^1.2.0
  date_picker_timeline: ^1.2.3
  web_socket_channel: ^2.1.0
  shimmer: ^2.0.0
  permission_handler: ^10.2.0
  app_settings: ^4.1.1
  connectivity: ^3.0.6
  url_launcher: ^6.1.10
  flutter_linkify: ^5.0.2
  flutter_web_browser: ^0.14.0
  flutter_local_notifications: ^6.0.0
  package_info: ^2.0.2
  device_info: ^2.0.2
  any_link_preview:
    path: packages/any_link_preview-2.0.1-rc
  flutter_datetime_picker:
    git:
      url: https://github.com/AlexHartford/flutter_datetime_picker.git
      ref: master
  receive_sharing_intent: ^1.4.5
  marquee: ^2.2.0
  collection: ^1.15.0
  path_provider: ^2.0.2
  extended_nested_scroll_view: ^6.0.0
  pull_to_refresh_notification: ^2.2.0
  loading_more_list: ^4.1.0
  extended_image: ^4.1.0
  share_plus: ^6.3.1
  
  # Firebase
  firebase_auth: ^1.1.2
  firebase_messaging: ^10.0.2

  image_gallery_saver: '^1.7.1'
  qr_flutter: ^4.0.0
  # firebase_dynamic_links: ^3.0.0
  uni_links: ^0.5.1
  clipboard: ^0.1.3
  # fluttertoast: ^8.0.8
  another_flushbar: ^1.10.26

dependency_overrides:
  firebase_core_platform_interface: 4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/style/

  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/proxima_nova/ProximaNova-Black.otf
        - asset: assets/fonts/proxima_nova/ProximaNova-Bold.otf
        - asset: assets/fonts/proxima_nova/ProximaNova-Light.otf
        - asset: assets/fonts/proxima_nova/ProximaNova-Regular.otf
        - asset: assets/fonts/proxima_nova/ProximaNova-Sbold.otf
        - asset: assets/fonts/proxima_nova/ProximaNova-Thin.otf
        - asset: assets/fonts/proxima_nova/ProximaNova-Xbold.otf

    - family: Avenir
      fonts:
        - asset: assets/fonts/avenir/Avenir-Black.otf
        - asset: assets/fonts/avenir/Avenir-Light.otf
        - asset: assets/fonts/avenir/Avenir-Regular.otf

    - family: Metropolis
      fonts:
        - asset: assets/fonts/metropolis/Metropolis-Black.otf
        - asset: assets/fonts/metropolis/Metropolis-BlackItalic.otf
        - asset: assets/fonts/metropolis/Metropolis-Bold.otf
        - asset: assets/fonts/metropolis/Metropolis-BoldItalic.otf
        - asset: assets/fonts/metropolis/Metropolis-ExtraLight.otf
        - asset: assets/fonts/metropolis/Metropolis-ExtraLightItalic.otf
        - asset: assets/fonts/metropolis/Metropolis-Light.otf
        - asset: assets/fonts/metropolis/Metropolis-LightItalic.otf
        - asset: assets/fonts/metropolis/Metropolis-Medium.otf
        - asset: assets/fonts/metropolis/Metropolis-MediumItalic.otf
        - asset: assets/fonts/metropolis/Metropolis-Regular.otf
        - asset: assets/fonts/metropolis/Metropolis-RegularItalic.otf
        - asset: assets/fonts/metropolis/Metropolis-SemiBold.otf
        - asset: assets/fonts/metropolis/Metropolis-SemiBoldItalic.otf
        - asset: assets/fonts/metropolis/Metropolis-Thin.otf
        - asset: assets/fonts/metropolis/Metropolis-ThinItalic.otf

    - family: Aeonik
      fonts:
        - asset: assets/fonts/aeonik/Aeonik-Air.otf
          weight: 100
        - asset: assets/fonts/aeonik/Aeonik-AirItalic.otf
          weight: 100
          style: italic
          
        - asset: assets/fonts/aeonik/Aeonik-Thin.otf
          weight: 200
        - asset: assets/fonts/aeonik/Aeonik-ThinItalic.otf
          weight: 200
          style: italic

        - asset: assets/fonts/aeonik/Aeonik-Light.otf
          weight: 300
        - asset: assets/fonts/aeonik/Aeonik-LightItalic.otf
          weight: 300
          style: italic

        - asset: assets/fonts/aeonik/Aeonik-Regular.otf
          weight: 400
        - asset: assets/fonts/aeonik/Aeonik-RegularItalic.otf
          weight: 400
          style: italic

        - asset: assets/fonts/aeonik/Aeonik-Medium.otf
          weight: 500
        - asset: assets/fonts/aeonik/Aeonik-MediumItalic.otf
          weight: 500
          style: italic

        - asset: assets/fonts/aeonik/Aeonik-Medium.otf
          weight: 600
        - asset: assets/fonts/aeonik/Aeonik-MediumItalic.otf
          weight: 600
          style: italic

        - asset: assets/fonts/aeonik/Aeonik-Bold.otf
          weight: 700
        - asset: assets/fonts/aeonik/Aeonik-BoldItalic.otf
          weight: 700
          style: italic

        - asset: assets/fonts/aeonik/Aeonik-Bold.otf
          weight: 800
        - asset: assets/fonts/aeonik/Aeonik-BoldItalic.otf
          weight: 800
          style: italic

        - asset: assets/fonts/aeonik/Aeonik-Black.otf
          weight: 900
        - asset: assets/fonts/aeonik/Aeonik-BlackItalic.otf
          weight: 900
          style: italic